main_page/main_page/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('', include("mypage.urls"), name='mypage'),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )
    urlpatterns += staticfiles_urlpatterns()

main_page/mypage/urls.py
from django.contrib import admin
from django.urls import path

from mypage.views import IndexView, CVView, Index2View

app_name = "mypage"

urlpatterns = [
    path("", Index2View.as_view(), name="index2"),
    path("index", IndexView.as_view(), name="index"),
    path("cv", CVView.as_view(), name="cv"),
    path("cv2", CVView.as_view(), name="cv2"),
]

main_page/mypage/models.py
from django.db import models

# Create your models here.

main_page/mypage/views.py
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from django.utils.translation import gettext_lazy as _


class IndexView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "mypage/index.html"

    def get(self, request: Request) -> Response:
        # print('printing request: ', request)
        # print('printing request.LANGUAGE_CODE : ', request.LANGUAGE_CODE)
        # print('printing request.data: ', request.data)
        data = request.data
        data["data1"] = 'Some text'
        programing_skills = [["Python"], ["Django", "DRF"], ["HTML", "CSS", "Bootstrap", "Ajax", "Postman"],
                             ["Flask", "API", "Docker", "Swagger", "Aiogram"], ["SQLite", "MySQL", "PostgreSQL"],
                             ["Git", "GitHub", "GitLab"], ["NumPy", "Pandas", "Agile", "Odoo"],
                             ["OOP", "DRY", "SOLID", "CRUD", "KISS"]]
        # programing_skills = "Python, Django, DRF, Git, API, SQLite, MySQL, PostgreSQL, Flask, HTML, CSS, Bootstrap, Aiogram, Docker, Swagger, OOP, DRY, SOLID CRUD KISS principles, Ajax, NumPy, Pandas, Agile, Postman, GitHub, GitLab, Odoo framework "
        data["programing_skills"] = programing_skills
        other_skills = ["Team player", "Project Management", "Time management", "Administration", "Accounting"]
        data["other_skills"] = other_skills
        language_skills = ["English", "Russian", "Romanian", "Italian"]
        data["language_skills"] = language_skills
        project_one = ["Python", "Django", "DRF", "API", "SQLite", "HTML", "CSS", "Bootstrap", "Docker", "Swagger"]
        data["project_one"] = project_one
        project_two = ["Python", "Django", "DRF", "API", "SQLite", "HTML", "Bootstrap", "Docker"]
        data["project_two"] = project_two
        project_three = ["Python", "Aiogram", "API", "SQLite", "Docker"]
        data["project_three"] = project_three

        return Response(data)


class Index2View(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "mypage/index2.html"

    def get(self, request: Request) -> Response:
        # print('printing request: ', request)
        # print('printing request.LANGUAGE_CODE : ', request.LANGUAGE_CODE)
        # print('printing request.data: ', request.data)
        data = request.data
        data["data1"] = 'Some text'
        programing_skills = [["Python", "Django", "DRF", "Flask", "Git", "API"],
                             ["HTML", "CSS", "Bootstrap", "Ajax", "Postman"],
                             ["SQL", "PostgreSQL", "NumPy", "Pandas", "Agile", "Odoo"],
                             ["Docker", "Swagger", "Aiogram"],
                             ["OOP", "DRY", "SOLID", "CRUD", "KISS"]]
        # programing_skills = "Python, Django, DRF, Git, API, SQLite, MySQL, PostgreSQL, Flask, HTML, CSS, Bootstrap, Aiogram, Docker, Swagger, OOP, DRY, SOLID CRUD KISS principles, Ajax, NumPy, Pandas, Agile, Postman, GitHub, GitLab, Odoo framework "
        data["programing_skills"] = programing_skills
        other_skills = ["Team player", "Project Management", "Time management", "Administration", "Accounting"]
        data["other_skills"] = other_skills
        language_skills = ["English", "Russian", "Romanian", "Italian"]
        data["language_skills"] = language_skills
        project_one = ["Python", "Django", "DRF", "API", "SQLite", "HTML", "CSS", "Bootstrap", "Docker", "Swagger"]
        data["project_one"] = project_one
        project_two = ["Python", "Django", "DRF", "API", "SQLite", "HTML", "Bootstrap", "Docker"]
        data["project_two"] = project_two
        project_three = ["Python", "Aiogram", "API", "SQLite", "Docker"]
        data["project_three"] = project_three

        return Response(data)


class CVView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "mypage/cv.html"

    def get(self, request: Request) -> Response:
        data = request.data

        return Response(data)


class CVView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "mypage/cv2.html"

    def get(self, request: Request) -> Response:
        data = request.data

        return Response(data)

main_page/mypage/templates/mypage/cv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<style>
body {
        margin: 0;
        padding: 0;
        background-color: #FAFAFA;
        font: 12pt "Tahoma";
    }
    * {
        box-sizing: border-box;
        -moz-box-sizing: border-box;
    }
    .page {
        width: 21cm;
        min-height: 29.7cm;
        padding: 2cm;
        margin: 1cm auto;
        border: 1px #D3D3D3 solid;
        border-radius: 5px;
        background: white;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }
    .subpage {
        padding: 1cm;
        border: 5px red solid;
        height: 256mm;
        outline: 2cm #FFEAEA solid;
    }

    @page {
        size: A4;
        margin: 0;
    }
    @media print {
        .page {
            margin: 0;
            border: initial;
            border-radius: initial;
            width: initial;
            min-height: initial;
            box-shadow: initial;
            background: initial;
            page-break-after: always;
        }
    }
</style>
<body>
<div class="book">
    <div class="page">
        <div class="subpage">CV</div>
    </div>

</div>
</body>
</html>

main_page/mypage/templates/mypage/cv2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ get_current_language }}/css/normalize.css" type="text/css" media="screen">

</head>

<style>
    body {
        font-family: BOLD;
        margin: 0;
        padding: 0;
    {#         background-color: #FAFAFA; #} font: 12pt "Tahoma";
    }

    * {
        box-sizing: border-box;
        -moz-box-sizing: border-box;
    }

    .page {
        width: 21cm;
        min-height: 29.7cm;
        padding: 2cm;
        margin: 1cm auto;
    {#         border: 1px #D3D3D3 solid; #} border-radius: 5px;
    {#         background: white; #}{#         box-shadow: 0 0 5px rgba(0, 0, 0, 0.1); #}
    }

    .subpage {
    {#padding: 1cm;#}{# border: 1px red solid; #} height: 256mm;
    {#outline: 2cm #FFEAEA solid;#}{# background: #ffffff; #}

    }

    @font-face {
        font-family: myFirstFont;
        src: url(css/Tempestua_D.otf);
    }

    @font-face {
        font-family: mySecondtFont;
        src: url(css/Galleds_Stars.otf);
    }

    @font-face {
        font-family: myThirdFont;
        src: url(css/CarteBlanche_Demo.ttf);
    }

    @font-face {
        font-family: myFourthtFont;
        src: url(css/Bistecca.ttf);
    }

    .cv-container {
        padding: 15px;
        margin: 15px;
    }

    .name-container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 15vh;
    }

    .name-div {
        width: 50%;
        height: 50%;
    }

    .name-text-1 {
        size: A4;
        text-align: center;
        font-family: myFirstFont;
        font-size: 30px;
    }

    .name-text-2 {
        text-align: center;
        font-family: mySecondtFont;
        font-size: 15px;
    }

    .content-container {
        display: flex;
        flex-direction: row;
        height: 40vh;
        align-items: center;
    }

    .colzz {
        padding: 10px;
        flex: 50%;
        display: flex;
        flex-direction: column;
    }

    .colzz:nth-child(2) {
        border-left: 2px solid;
    }

    .right-align {
        align-items: flex-end;
    }

    .right-left {
        align-items: flex-start;
    }

    .content-header {
        font-size: 20px;
    }

    .content-mar-general {
        margin-bottom: 7px;
    }

    .content-mar-general-bot {
        margin-bottom: 15px;
    }

    .content-mar-bop {
        margin-bottom: 1px;
    }

    .content-desc-font {
        font-size: 12px;
    }

    .photo {
        height: 200px;
    }

    .parent {
        position: relative;
        top: 0;
        left: 20%;
    }

    .image1 {
        position: relative;
        top: 0;
        left: 0;
        width: 25%;
        height: 130px;
        border-radius: 50%;
        outline: solid #fee064;
        background: #fee064;
    }

    .image2 {
        position: absolute;
        top: 0;
        left: 65px;
        width: 35%;
        border-radius: 50%;
    }

    .grayscale {
        filter: grayscale(90%);
    }

    .container {
        background-color: rgb(192, 192, 192);
        width: 60%;
        height: 5px;
        border-radius: 15px;
        direction: rtl;
    }

    .skill {
        background-color: rgb(116, 194, 92);
        color: white;
        padding: 1%;
        text-align: right;
        border-radius: 15px;

    }

    .python {
        width: 80%;
    }

    .django {
        width: 70%;
    }

    .html-css {
        width: 50%;
    }

    .progress-bar-marg {
        margin-bottom: 10px;
        margin-top: 2px;
    }

    .content-mar-lang-top {
        margin-top: 15px;
    }

    .footer-margin-top {
        margin-top: 65px;
    }

    @page {
        size: A4;
        margin: 0;
    }

    @media print {
        .page {
            margin: 0;
            border: initial;
            border-radius: initial;
            width: initial;
            min-height: initial;
            box-shadow: initial;
            background: initial;
            page-break-after: always;
        }
    }
</style>
<body>
<div class="book">
    <div class="page">
        <div class="subpage">
            <div class="cv-container photo ">
                <div class="parent ">
                    <div class="center">
                        <div class="image1"></div>
                        <img class="image2 grayscale " src="img/my_mug.jpeg"/>
                    </div>
                </div>
            </div>
            <div class="name-container">
                <div class="name-div ">
                    <div class="name-text-1">Alexandr Basso</div>
                    <div class="name-text-2">Python Developer</div>
                </div>

            </div>

            <div class="content-container name-text-2">
                <div class="colzz right-align">
                    <div class="content-header content-mar-general"><b>demo projects</b></div>
                    <div>visit my website:</div>
                    <div class="content-mar-general-bot content-desc-font">
                        <a href="http://89.223.124.144:8002/">http://89.223.124.144:8002/</a>
                    </div>

                    <div class="content-header content-mar-general"><b>competencies</b></div>

                    <div class="name-text-2">Python</div>
                    <div class="container progress-bar-marg ">
                        <div class="skill python "></div>
                    </div>

                    <div class="name-text-2 ">HTML, CSS</div>
                    <div class="container progress-bar-marg">
                        <div class="skill html-css"></div>
                    </div>

                    <div class="name-text-2">Django</div>
                    <div class="container progress-bar-marg content-mar-general-bot ">
                        <div class="skill django"></div>
                    </div>



                    <div>DRF, Flask, Git</div>
                    <div>API, Docker, Swagger</div>
                    <div>SQLite, MySQL, PostgreSQL</div>
                    <div>NumPy, Pandas, , Aiogram, Odoo</div>
                    <div>OOP, DRY, SOLID, CRUD, KISS</div>


                    <div class="content-header content-mar-general content-mar-lang-top">
                        <b>languages</b>
                    </div>
                    <div>English: TOEFL C1</div>
                    <div>Russian: Native</div>
                    <div>Romanian: B2</div>
                    <div>Italian: A1</div>


                </div>


                <div class="colzz right-left">

                    <div class="content-header content-mar-general"><b>courses</b></div>
                    <div><b>january 2023 - present</b></div>
                    <div class="content-mar-general-bot content-desc-font">Skillbox - Python Developer course</div>


                    <div class="content-header content-mar-general"><b>experience</b></div>
                    <div><b>august 2022 - october 2022</b></div>
                    <div class="content-mar-bop content-desc-font">OilTech SRL, MD - Python Developer</div>
                    <div><b>2021- 2022</b></div>
                    <div class="content-mar-bop content-desc-font">Centro Basso Prezzo SA, MD - Executive Director</div>
                    <div><b>2020 - 2023</b></div>
                    <div class="content-mar-bop content-desc-font">vaworks.biz, MD - Director General</div>
                    <div><b>2017 - 2020</b></div>
                    <div class="content-mar-bop content-desc-font">Unifun, MD - Account Manager</div>
                    <div><b>2015 - 2017</b></div>
                    <div class="content-mar-bop content-desc-font">SC BASpes SRL, RO - Director General</div>
                    <div><b>2012 - 2015</b></div>
                    <div class="content-mar-general-bot content-desc-font">ASCOLIS.R.L, MD - Acquisition Manager</div>

                    <div class="content-header content-mar-general"><b>education</b></div>
                    <div>Erasmus University</div>
                    <div><b>2011 - 2012</b></div>
                    <div class="content-mar-bop content-desc-font">Master - Entrepreneurship and Strategy</div>
                    <div><b>2008 - 2011</b></div>
                    <div class="content-desc-font">Bachelor - International Econ. & Business</div>


                </div>

            </div>

            <div class="cv-container name-text-2 footer-margin-top">
                alexandr.basso@gmail.com - +37378870065
            </div>

        </div>
    </div>
</div>

</div>
</body>
</html>

main_page/mypage/templates/mypage/cv3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ get_current_language }}/css/normalize.css" type="text/css" media="screen">

</head>

<style>
    body {
        font-family: BOLD;
        margin: 0;
        padding: 0;
    {#         background-color: #FAFAFA; #} font: 12pt "Tahoma";
    }

    * {
        box-sizing: border-box;
        -moz-box-sizing: border-box;
    }

    .page {
        width: 21cm;
        min-height: 29.7cm;
        padding: 2cm;
        margin: 1cm auto;
        {#border: 1px #D3D3D3 solid;#}
        border-radius: 5px;
        background: white;
    {#         box-shadow: 0 0 5px rgba(0, 0, 0, 0.1); #}
    }

    .subpage {
    {#padding: 1cm;#}{# border: 1px red solid; #} height: 256mm;
    {#    outline: 2cm #FFEAEA solid;#}
    {# background: #ffffff; #}

    }

    @font-face {
        font-family: myFirstFont;
        src: url(css/Tempestua_D.otf);
    }

    @font-face {
        font-family: mySecondtFont;
        src: url(css/Galleds_Stars.otf);
    }

    @font-face {
        font-family: myThirdFont;
        src: url(css/CarteBlanche_Demo.ttf);
    }

    @font-face {
        font-family: myFourthtFont;
        src: url(css/Bistecca.ttf);
    }

    .cv-container {
        padding: 15px;
        margin: 15px;
    }

    .name-container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 15vh;
    }

    .name-div {
        width: 50%;
        height: 50%;
        margin-bottom: 50px;
    }

    .name-text-1 {
        size: A4;
        text-align: center;
        font-family: myFirstFont;
        font-size: 30px;
    }

    .name-text-2 {
        text-align: center;
        font-family: mySecondtFont;
        font-size: 15px;
    }

    .content-container {
        display: flex;
        flex-direction: row;
        height: 40vh;
        align-items: center;
    }

    .colzz {
        padding: 10px;
        flex: 50%;
        display: flex;
        flex-direction: column;
    }

    .colzz:nth-child(2) {
        border-left: 2px solid;
    }

    .right-align {
        align-items: flex-end;
    }

    .right-left {
        align-items: flex-start;
    }

    .content-header {
        font-size: 20px;
    }

    .content-mar-general {
        margin-bottom: 7px;
    }

    .content-mar-general-bot {
        margin-bottom: 15px;
    }

    .content-mar-bop {
        margin-bottom: 1px;
    }

    .content-desc-font {
        font-size: 12px;
    }

    .photo {
        height: 200px;
    }

    .parent {
        position: relative;
        top: 0;
        left: 20%;
    }

    .image1 {
        position: relative;
        top: 0;
        left: 0;
        width: 25%;
        height: 130px;
        border-radius: 50%;
        outline: solid #fee064;
        background: #fee064;
    }

    .image2 {
        position: absolute;
        top: 0;
        left: 65px;
        width: 35%;
        border-radius: 50%;
    }

    .grayscale {
        filter: grayscale(10%);
    }

    .container {
        background-color: rgb(192, 192, 192);
        width: 60%;
        height: 5px;
        border-radius: 15px;
        direction: rtl;
    }

    .skill {
        background-color: rgb(116, 194, 92);
        color: white;
        padding: 1%;
        text-align: right;
        border-radius: 15px;

    }

    .python {
        width: 80%;
    }

    .django {
        width: 70%;
    }

    .html-css {
        width: 50%;
    }

    .progress-bar-marg {
        margin-bottom: 10px;
        margin-top: 2px;
    }

    .content-mar-lang-top {
        margin-top: 15px;
    }

    .content-mar-lang-top-2 {
        margin-top: 3px;

    }

    .footer-margin-top {
        margin-top: 55px;
    }

    .img-links-resizer {
        max-width: 15%;
        min-width: auto;
        margin: auto;
        margin-right: 15px;
        margin-left: 125px;
    }

    .img-links-resizer-2 {
        margin-right: 2px;
        margin-left: 15px;

    }

    @page {
        size: A4;
        margin: 0;
    }

    @media print {
        .page {
            margin: 0;
            border: initial;
            border-radius: initial;
            width: initial;
            min-height: initial;
            box-shadow: initial;
            background: initial;
            page-break-after: always;
        }
    }
</style>
<body>
<div class="book">
    <div class="page">
        <div class="subpage">
            <div class="cv-container photo ">
                <div class="parent ">
                    <div class="center">
                        <div class="image1"></div>
                        <img class="image2 grayscale " src="img/my_mug.jpeg"/>
                    </div>
                </div>
            </div>
            <div class="name-container">
                <div class="name-div ">
                    <div class="name-text-1">Alexandr Basso</div>
                    <div class="name-text-2">Python Developer</div>
                </div>

            </div>

            <div class="content-container name-text-2">
                <div class="colzz right-align">
                    <div class="content-header content-mar-general"><b>demo projects</b></div>
                    <div>visit my website:</div>
                    <div class="content-mar-general-bot content-desc-font">
                        <a href="http://89.223.124.144:8002/">http://89.223.124.144:8002/</a>
                    </div>

                    <div class="content-header content-mar-general"><b>competencies</b></div>

                    <div class="name-text-2">Python</div>
                    <div class="container progress-bar-marg ">
                        <div class="skill python "></div>
                    </div>

                    <div class="name-text-2 ">HTML, CSS</div>
                    <div class="container progress-bar-marg">
                        <div class="skill html-css"></div>
                    </div>

                    <div class="name-text-2">Django</div>
                    <div class="container progress-bar-marg content-mar-general-bot ">
                        <div class="skill django"></div>
                    </div>


                    <div>DRF, Flask, Git, Linux</div>
                    <div>API, Bash, Docker, Swagger</div>
                    <div>SQLite, MySQL, PostgreSQL, Postman API</div>
                    <div>NumPy, Pandas, Aiogram, Odoo</div>
                    <div>OOP, DRY, SOLID, CRUD, KISS</div>

                    <div class="content-mar-lang-top">
                        <a href="https://www.linkedin.com/in/alexandrbasso/"><img
                                class="img-links-resizer"
                                src="img/linkedin.png" alt="linkedin"></a>
                        <a href="https://github.com/AlexBasso"><img class="img-links-resizer img-links-resizer-2"
                                                                    src="img/github-sign.png"
                                                                    alt="githubimg"></a>
                    </div>
                    <div class="content-header content-mar-general content-mar-lang-top-2">
                        <b>languages</b>
                    </div>
                    <div>English: TOEFL C1</div>
                    <div>Russian: Native</div>
                    <div>Romanian: B2</div>
                    <div>Italian: A1</div>


                </div>


                <div class="colzz right-left">


                    <div class="content-header content-mar-general"><b>experience</b></div>
                    <div><b>june 2023 - present</b></div>
                    <div class="content-mar-bop content-desc-font">Ascoli SRL, MD - Python/Django developer</div>
                    <div><b>august 2022 - november 2022</b></div>
                    <div class="content-mar-general-bot content-desc-font">OilTech SRL, MD - Python Developer</div>

                    <div class="content-header content-mar-general"><b>courses</b></div>
                    <div><b>january 2023 - present</b></div>
                    <div class="content-mar-general-bot content-desc-font">Skillbox - Python Developer course</div>

                    <div class="content-header content-mar-general"><b>other experience</b></div>

                    <div><b>2021 - 2022</b></div>
                    <div class="content-mar-bop content-desc-font">Centro Basso Prezzo SA, MD - Executive Director</div>
                    <div><b>2020 - 2023</b></div>
                    <div class="content-mar-bop content-desc-font">BA Spes Total, MD - Director General</div>
                    <div><b>2017 - 2020</b></div>
                    <div class="content-mar-bop content-desc-font">Unifun, MD - Account Manager</div>
                    <div><b>2015 - 2017</b></div>
                    <div class="content-mar-bop content-desc-font">SC BASpes SRL, RO - Director General</div>
                    <div><b>2012 - 2015</b></div>
                    <div class="content-mar-bop content-desc-font">Aascoli SRL, MD - Acquisition Manager</div>


                    <div class="content-header content-mar-general"><b>education</b></div>
                    <div><b>2008 - 2012</b></div>
                    <div class="content-mar-bop content-desc-font">Master - Entrepreneurship and Strategy</div>
                    <div class="content-desc-font">Bachelor - International Econ. & Business</div>


                </div>

            </div>

            <div class="cv-container name-text-2 footer-margin-top">
                alexandr.basso@gmail.com - +37378870065
            </div>

        </div>
    </div>
</div>

</div>
</body>
</html>

main_page/mypage/templates/mypage/nav-bar.html
{% load i18n %}

<style>
    .position-left {
        padding-top: 3px;
        padding-left: 4px;
    }



    .container-params-contact {
        text-align: right;
    }
</style>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'mypage:index' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

            <li class="nav-item">
                <a class="nav-link" href="#projects-id">Projects</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#about-id">About me</a>
            </li>

            <li class="nav-item position-left">
                <form class="position-left" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}
                                    selected{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Go">
                </form>
            </li>


            <li class="nav-item">
                <div class="container container-params-contact">

                    <h4>

                        <a href="https://www.linkedin.com/in/alexandrbasso/"><img
                                class="img-links-resizer "
                                src="img/linkedin.png" alt="linkedin"></a>
                        <a href="mailto:alexandr.basso@gmail.com"><img class="img-links-resizer" src="img/gmail.png"
                                                                       alt="email"></a>
                        <a href="https://github.com/AlexBasso"><img class="img-links-resizer" src="img/github-sign.png"
                                                                    alt="githubimg"></a>
                        <a href="tel:+37378870065"><img class="img-links-resizer" src="img/smartphone.png" alt="mobile"></a>
                        <a href="https://drive.google.com/file/d/19crFMLNCoBt-9r3OFqlZYo9NMSD2n67c/view?usp=sharing"
                           class="btn btn-outline-primary download-button" target="_blank" role="button">Download
                            CV</a>
                    </h4>
                </div>
            </li>
        </ul>
    </div>
</nav>